apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 3 # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: 421954350274.dkr.ecr.us-east-1.amazonaws.com/hotstar:13
        ports:
        - containerPort: 3000  # Port your application listens on
